### ISSUE TITLE
Strange exit(0) on "valid" input

### ISSUE THREAD

**Issue by rvosa** [blackrim/treePL#12]
Hi,

on one of our data sets we're getting an NaN somewhere that is causing treePL to exit. Looking at the code a bit we're a bit puzzled by what's happening around here:

https://github.com/blackrim/treePL/blob/master/src/pl_calc_parallel.cpp#L684

We can't figure out why that padding (or indeed, anything) is still happening after the exit, and what the intent is here. If I comment the exit out and re-run we somehow do end up with an ultrametric tree with the calibration point at the right age, but we're not particularly confident about our results. What do you think could be happening? Can we send you a simple example so you can replicate what's going on?

Thanks,

Rutger

**Comment by hettling** [comment]
Hi, I found many more examples where treePL exits even with only very few calibration points at a very low level in my trees. The exit(0) in the code still looks like some remnant from debugging, but I am really not sure. Has anyone an idea of how to address this issue?
Thanks in advance,
Hannes

**Comment by blackrim** [comment]
Yes, sorry about that. That is some debugging code. The gradient is simply reset if nan is found there.
