### ISSUE TITLE
'wiggle' option

### ISSUE THREAD

**Issue by amritchie** [blackrim/treePL#14]
Hi,
I read in the Bioinformatics paper that treePL provides a ‘wiggle’ option that reports divergence times within 2 log-likelihood units of the best known likelihood.  I’d like to use this, but can’t find it listed on the wiki.

I'd just like to know if it is implemented and, if so, what it is called.

Best,
A. Ritchie

**Comment by blackrim** [comment]
Sorry for the delay here. Missed this issue. 
It is 
mapspace 
in the config file.
