### ISSUE TITLE
crashes more often than not

### ISSUE THREAD

**Issue by rvosa** [blackrim/treePL#15]
In seemingly simple cases, with few calibration points such as when fixing the root to some arbitrary number, treePL crashes:

	initial calc: 1e+15
	problem initializing. trying again.
	attempting to get feasible start rates/dates.
	new start rate -0.25374025
	initial calc: 1e+15
	problem initializing. trying again.
	attempting to get feasible start rates/dates.
	new start rate -0.25374025
	initial calc: 1e+15
	problem initializing. trying again.
	attempting to get feasible start rates/dates.
	new start rate -0.25374025
	initial calc: 1e+15
	problem initializing. trying again.
	attempting to get feasible start rates/dates.
	new start rate -0.25374025
	initial calc: 1e+15
	problem initializing. trying again.
	attempting to get feasible start rates/dates.
	new start rate -0.25374025
	initial calc: 1e+15
	problem initializing. trying again.
	attempting to get feasible start rates/dates.
	new start rate -0.25374025
	initial calc: 1e+15
	problem initializing. trying again.
	attempting to get feasible start rates/dates.
	new start rate -0.25374025
	initial calc: 1e+15
	problem initializing. trying again.
	attempting to get feasible start rates/dates.
	new start rate -0.25374025
	initial calc: 1e+15
	problem initializing. trying again.
	attempting to get feasible start rates/dates.
	new start rate -0.25374025
	initial calc: 1e+15
	problem initializing. trying again.
	attempting to get feasible start rates/dates.
	new start rate -0.25374025
	initial calc: 1e+15
	Failed setting feasible start rates/dates after 10 attempts. Aborting.

**Comment by blackrim** [comment]
Hm, that is strange. Can you attach the example? This isn't the case with the simple cases that I have.

**Comment by rvosa** [comment]
Argh, can't reproduce it now... sorry, will get back to you on this...

**Comment by rvosa** [comment]
Actually, I figured it out: I was generating config files on my end (from a script) and in some cases not a single calibration point had ended up in the config file. I appreciate that undefined behavior could ensue if I do that. Sorry - my bad, disregard this.

**Comment by blackrim** [comment]
No problems.
