### ISSUE TITLE
treePL with Mac OS 11.1

### ISSUE THREAD

**Issue by Latastia** [blackrim/treePL#18]
Hi,

I have a quick question: it seems I can't get treePL to run since I've updated my Mac Os to "El Capitan" (11.1). Is that a known problem, or is it just me having made a mistake or confusing something?

Thank you,
Johannes

**Comment by josephwb** [comment]
Are you trying to compile it yourself? Apple compilers continue to be a headache.

Have you tried the distributed binary `treePL_mac10_9_binary.tgz`? It works for me with "El Capitan".

**Comment by Latastia** [comment]
Hi,

Actually I have been using a version that I had installed one year ago. And I didn’t do any updates in the meantime. Is that the same version from last February?

And just to make sure that I just didn’t screw up with the commands: I go into src directory and then type „treePL (filename)“. Is that correct? I mean I did it many times before, but the last time was last summer or so, and maybe I now made a mistake in this very simple step.

Thank you,
Johannes



Am 10.02.2016 um 14:18 schrieb Joseph W. Brown <notifications@github.com<mailto:notifications@github.com>>:


Are you trying to compile it yourself? Apple compilers continue to be a headache.

Have you tried the distributed binary treePL_mac10_9_binary.tgz? It works for me with "El Capitan".

**Comment by josephwb** [comment]
If you type:
```
./treePL
```
without any arguments you should get:
```
./treePL 
treePL version 1.0
you need more arguments.
usage: treePL configfile
```
If you don't then there is a problem. Try the mac binary at the top of the repo:
```
tar -xvzf reePL_mac10_9_binary.tgz
./treePL
```

**Comment by josephwb** [comment]
To check if things with the mac binary work, do:
```
tar -xvzf reePL_mac10_9_binary.tgz
cd examples
../treePL test.cppr8s
```

**Comment by Latastia** [comment]
If you type:

./treePL


without any arguments you should get:

./treePL
treePL version 1.0
you need more arguments.
usage: treePL configfile


If you don't then there is a problem. Try the mac binary at the top of the repo:

tar -xvzf reePL_mac10_9_binary.tgz
./treePL

For some reason it didn’t find the command when I was doing this. I’ll check again (am currently not at my laptop where treePL is installed) and let you know how it went. Thanks again!

Johannes

**Comment by Latastia** [comment]
Thanks!


Am 10.02.2016 um 14:39 schrieb Joseph W. Brown <notifications@github.com<mailto:notifications@github.com>>:


To check if things with the mac binary work, do:

tar -xvzf reePL_mac10_9_binary.tgz
cd examples
../treePL test.cppr8s

**Comment by Latastia** [comment]
This is what I’m getting (see below). And I originally installed the mac10_9 binary back in December 2014, so it’s the last version.


Johanness-MacBook-Pro:src latastia$ ./treePL
dyld: Library not loaded: /usr/lib64/libadolc.1.dylib
  Referenced from: /Applications/treePL/src/./treePL
  Reason: image not found
Trace/BPT trap: 5




Am 10.02.2016 um 14:38 schrieb Joseph W. Brown <notifications@github.com<mailto:notifications@github.com>>:


If you type:

./treePL


without any arguments you should get:

./treePL
treePL version 1.0
you need more arguments.
usage: treePL configfile


If you don't then there is a problem. Try the mac binary at the top of the repo:

tar -xvzf reePL_mac10_9_binary.tgz
./treePL


—
Reply to this email directly or view it on GitHub<https://github.com/blackrim/treePL/issues/18#issuecomment-182380642>.

--------------
Prof. Dr. Johannes Müller
Museum für Naturkunde
Leibniz-Institut für Evolutions- und Biodiversitätsforschung
an der Humboldt-Universität zu Berlin
Invalidenstr. 43
D-10115 Berlin, Germany
Phone: +49 30 2093 8805
Fax: +49 30 2093 8565
www.muellerlaboratory.wordpress.com<http://www.muellerlaboratory.wordpress.com>

**Comment by josephwb** [comment]
Looks like you are trying to run a version you compiled yourself (i.e. you are in directory `src`). Did you try the commands above for the binary? Go to the top of the treePL directory and type:
```
tar -xvzf treePL_mac10_9_binary.tgz
cd examples
../treePL test.cppr8s
```

**Comment by Latastia** [comment]
That worked, thanks! :-)

Am 10.02.2016 um 21:16 schrieb Joseph W. Brown <notifications@github.com<mailto:notifications@github.com>>:


Looks like you are trying to run a version you compiled yourself (i.e. you are in directory src). Did you try the commands above for the binary? Go to the top of the treePL directory and type:

tar -xvzf treePL_mac10_9_binary.tgz
cd examples
../treePL test.cppr8s
