### ISSUE TITLE
Updated Mac install with homebrew

### ISSUE THREAD

**Issue by jonchang** [blackrim/treePL#20]
I managed to get treePL compiled with some homebrew magic. This will hopefully make it much easier for people get treepl compiled and running. I will look into using this hard-won knowledge to update the makefiles, etc. to make things easier on both mac and linux. 

https://github.com/blackrim/treePL/wiki/Installation#mac
https://github.com/jonchang/homebrew-biology/blob/master/treepl.rb

**Comment by josephwb** [comment]
Sweet, thanks.
JWB

**Comment by josephwb** [comment]
I just tried it on an older mac and it worked fine. Minor difference with
the wiki instructions: when I tried it I get:

$ brew install treepl
Error: jonchang/biology/treepl is a head-only formula
Install with `brew install --HEAD jonchang/biology/treepl`

JWB

**Comment by josephwb** [comment]
Erg. Test just completed with failure:
```
...
Error: jonchang/biology/treepl: failed
execution expired
/usr/local/Library/Homebrew/formula.rb:1456:in `gets'
/usr/local/Library/Homebrew/formula.rb:1456:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1429:in `open'
/usr/local/Library/Homebrew/formula.rb:1429:in `system'
/usr/local/Library/Taps/jonchang/homebrew-biology/treepl.rb:79:in `block (3 levels) in <class:Treepl>'
/usr/local/Library/Taps/jonchang/homebrew-biology/treepl.rb:78:in `each'
/usr/local/Library/Taps/jonchang/homebrew-biology/treepl.rb:78:in `block (2 levels) in <class:Treepl>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:125:in `chdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:125:in `cd'
/usr/local/Library/Taps/jonchang/homebrew-biology/treepl.rb:77:in `block in <class:Treepl>'
/usr/local/Library/Homebrew/formula.rb:1334:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1328:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by jonchang** [comment]
I've updated the install instruction and changed the formula so it doesn't run quite so many tests and hit the test timeout.

**Comment by josephwb** [comment]
Still failing (log below). Also, I notice that it is only using 1 processor for the cv analysis. This was the entire reason for using OPENMP in the first place. Is something off there?

```
==> Sandbox log
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny mach-lookup com.apple.ocspd
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny mach-lookup com.apple.ocspd
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny mach-lookup com.apple.ocspd
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny mach-lookup com.apple.ocspd
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny mach-lookup com.apple.ocspd
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny mach-lookup com.apple.ocspd
May  1 07:35:00 kernel[0]: Sandbox: appleeventsd(50) deny mach-lookup com.apple.ocspd
May  1 07:35:04 sandboxd[43604]: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:04 sandboxd[43604]: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:04 sandboxd[43604]: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:04 sandboxd[43604]: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:04 sandboxd[43604]: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:04 sandboxd[43604]: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:05 sandboxd[43604]: appleeventsd(50) deny file-read-metadata /Library
May  1 07:35:05 sandboxd[43604]: appleeventsd(50) deny file-read-metadata /Library
Error: jonchang/biology/treepl: failed
execution expired
/usr/local/Library/Homebrew/formula.rb:1456:in `gets'
/usr/local/Library/Homebrew/formula.rb:1456:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1429:in `open'
/usr/local/Library/Homebrew/formula.rb:1429:in `system'
/usr/local/Library/Taps/jonchang/homebrew-biology/treepl.rb:79:in `block (3 levels) in <class:Treepl>'
/usr/local/Library/Taps/jonchang/homebrew-biology/treepl.rb:78:in `each'
/usr/local/Library/Taps/jonchang/homebrew-biology/treepl.rb:78:in `block (2 levels) in <class:Treepl>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:125:in `chdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:125:in `cd'
/usr/local/Library/Taps/jonchang/homebrew-biology/treepl.rb:77:in `block in <class:Treepl>'
/usr/local/Library/Homebrew/formula.rb:1334:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1328:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by jonchang** [comment]
I hadn't noticed that it wasn't being parallelized. It seems to be linking correctly against openMP (`libgomp`) so I'm not sure why it's not threading properly...

```
 $ otool -L `brew --prefix treepl`/bin/treePL
/usr/local/opt/treepl/bin/treePL:
	/usr/local/Cellar/treepl/HEAD/libexec/lib64/libadolc.1.dylib (compatibility version 3.0.0, current version 3.1.0)
	/usr/local/lib/libnlopt_cxx.0.dylib (compatibility version 9.0.0, current version 9.2.0)
	/usr/local/opt/gcc/lib/gcc/5/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.21.0)
	/usr/local/opt/gcc/lib/gcc/5/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/lib/gcc/5/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

Is treePL parallelized only when doing cross validation, or does it also parallelize divergence time estimation?

**Comment by josephwb** [comment]
Only for cv analysis, although I have code to use it more generally (not finished, and not pushed).

**Comment by jonchang** [comment]
OK, it looks like the test files aren’t setting `nthreads=2` and thus aren’t using threading.

**Comment by josephwb** [comment]
Doh!

**Comment by jonchang** [comment]
I've confirmed that the homebrew formula works on CentOS linux with Linuxbrew. I'm going to spin up an ubuntu VM later this week to confirm the install/build instructions and then submit a real PR.

**Comment by longrich** [comment]
Running into some problems installing this:

==> Applying 19.patch
/usr/bin/patch -g 0 -f -p1 -i /private/tmp/treepl--patch-20161015-11168-1d94slk/19.patch
patching file src/Makefile.in
Hunk #1 FAILED at 68.
Hunk #2 FAILED at 86.
2 out of 2 hunks FAILED -- saving rejects to file src/Makefile.in.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/treepl--patch-20161015-11168-1d94slk/19.patch


any suggestions?

**Comment by josephwb** [comment]
Just tried and this seems to work for me. :bowtie:

**Comment by pimientoc** [comment]
Hello, I tried installing treePL in different mac (different versions, but my main mac is macOS Sierra) and I always get the same errors. 

Using Homebrew, when I try `brew install -v treepl`  I get:
"Error: No available formula with the name "adol-c". 

I tried installing adol-c following the instructions provided in the treePL installation wiki, but when I try `./configure --with-openmp-flag=-fopenmp --prefix=/usr` I get the error: 
"Prefix /Users/_myuser_/adolc_base not writable
  please run ./configure --prefix=DIR
  with a writable directory path otherwise administrator privilages
  will be required to run `make install'.

I searched online for tips on how to get around that error. One was to use: `./configure --with-openmp-flag=-fopenmp --libdir=/usr/lib` but it didn't work either. I get the same error message, and this other message: 
To successfully compile and run programs using the ADOL-C shared library do
  the following things:
     compiling:
        * add "-I/Users/_myuser_/adolc_base/include" to your compiler call
     linking:
        * add "-L/Users/_myuser_/adolc_base/lib64 -ladolc" to your linker call
        * extend your linker call by "-Wl,--rpath -Wl,/Users/myuser/adolc_base/lib64"
          (if you wish to skip the point "executing")
     executing (do one of the following things):
        * add /Users/_myuser_/adolc_base/lib64 to your LD_LIBRARY_PATH variable
        * ask your system administrator for adding /Users/_myuser_/adolc_base/lib64 to
          the global file containing library search paths (/etc/ld.so.conf)
     (or use the static library by replacing
        "-L/Users/_myuser_/adolc_base/lib64 -ladolc" with
        "/Users/_myuser_/adolc_base/lib64/libadolc.a" when linking).

As you probably realized already, I am not the most knowledgable person in terms if informatics, but I just want to be able to use treePL for my research :(.

I appreciate any advice you can provide me,
Thanks in advance.

**Comment by jonchang** [comment]
try `brew tap homebrew/science` then `brew install jonchang/biology/treepl`

I am working on a better way to get this installed but it will be a few months before I have the bandwidth to do so

**Comment by pimientoc** [comment]
That worked. Thanks!!!!

**Comment by kyledexter** [comment]
I am trying to install treePL on a mac running OS High Sierra 10.13.3.

I successfully installed NLopt (I think).

When trying to install treepl following the mac instructions on the install wiki (via the homebrew route), I am failing. Installing homebrew seemed to go fine. When I enter:
>brew install -v treepl

I receive this error:
Error: No available formula with the name "adol-c"

I tried installing adol-c separately (downloading from https://projects.coin-or.org/ADOL-C), using the recommended command under the linux instructions (because I wanted to make sure to tick that flag as specified in installation wiki), namely:
>sudo ./configure --with-openmp-flag=-fopenmp --prefix=/usr

But, that fails with this error:
clang: error: unsupported option '-fopenmp'

I also tried going through the the deps folder (after unpacking treepl.tar.gz file in Caches/Homebrew), but when I enter the recommended command:
>autoreconf -fi

I get this response:
autoreconf: 'configure.ac' or 'configure.in' is required

And then when I try the aforementioned line:
>sudo ./configure --with-openmp-flag=-fopenmp --prefix=/usr

I get this:
sudo: ./configure: command not found


Any help appreciated!

**Comment by josephwb** [comment]
@kyledexter gcc (annoyingly!) points to clang on mac, which does not support the `-fopenmp` flag.

Do you have GNU gcc? You can install it with homebrew. It will get installed in somewhere like ` usr/local/bin/g++-7` (you may have a different version). You can then edit the existing treePL `Makefile` to have:
```
CC := gcc=/usr/local/bin/gcc-7
CP := g++=/usr/local/bin/g++-7
```
and then `make`. You can accomplish the same thing by passing the relevant parameters to `./configure`. Do `./configure --help` to see what those options are.

This will deal with the openmp issue. Whether the dependencies are installed correctly? ¯\_(ツ)_/¯ You will want to recompile adol-c to have openmp support as above.

HTH. :bowtie:

**Comment by Cactusolo** [comment]
@jonchang 
I ran "brew test -v treepl"
got error:
==> /usr/local/Cellar/treepl/2017.05.23/bin/treePL clock.cppr8s
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Referenced from: /usr/local/Cellar/treepl/2017.05.23/bin/treePL
  Reason: image not found
Error: brewsci/bio/treepl: failed

**Comment by jonchang** [comment]
@Cactusolo please file an issue at https://github.com/brewsci/homebrew-bio/issues and fill out the issue template, thanks.

**Comment by BiodeB** [comment]
Dear Experts,

I have installed treepl using brew command `brew install brewsci/bio/treepl` but after that when I type treepl it displays `treepl: command not found`. The testing command  `brew test -v treep` shows long list run. 
What to do kindly guide me.
Thanks.

**Comment by Cactusolo** [comment]
Hi BiodeB,

I'm not an expert, but I'm frequent treepl user. I have installed treepl in the same way as you did. It works fine on my end.

Please make sure you call `treePL`

![image](https://user-images.githubusercontent.com/7811840/104851433-430ba300-58f5-11eb-8340-81cbcbcb4577.png)

**Comment by BiodeB** [comment]
Thanks Dr. Cactusolo, 

I was wrong, Now its working.
