### ISSUE TITLE
How drive treePL to estimate divergence time under strict global clock model?

### ISSUE THREAD

**Issue by CalamusLiber** [blackrim/treePL#21]
Dear author,

I would like to use treePL to estimate divergence time of a simulated phylogeny under clock model not relaxed one. How can I set the configuration file? I know r8s has LF method with nrates=1, but I have not find the corresponding options in treePL. Or the only way is to set a very large smoothing value, like 100000 or even larger?

Thanks and best wishes,
Liang

**Comment by blackrim** [comment]
This is a feature that would be nice to have. I will go ahead and add it.

**Comment by evolucionario** [comment]
Agree. It would be nice to use the TreePL machinery to estimate under a strict clock model using full likelihood (no penalty term or smoothing parameter). Those likelihood values would be more easily comparable.

**Comment by evolucionario** [comment]
Is the strict-clock model coming soon?

**Comment by evolucionario** [comment]
So, setting a smoothing value very high would be equivalent to estimate under a strict clock but is there a way of obtaining the log-likelihood value (i.e. without the penalty term)?

**Comment by blackrim** [comment]
Basically, yes. It will require the rates to be the same
