### ISSUE TITLE
how to choose the best smoothing from treePL

### ISSUE THREAD

**Issue by ghost** [blackrim/treePL#22]
Hi,
I also attached my questions here, hope the answers would be helpful for other people, or some other people can help as well.

I'm using treePL to do the dating. and  I acknowledged that the smoothing parameter is very important, which affects the penalty for rate variation over the tree.

So before I do the dating, I have conducted cross-validation procedure (thorough, prime, randomcv) to determine the best smoothing parameter with different "smooth =" settings (e.g.,smooth = 0.1,1,10,100,1000,10000) in the cross-validation
configure file.

now I'm confused facing these “priming” results, which should I choose? or none of them are best?

When "smooth = 0.1", the result is "best: 1(1) bestad: 1 (1) bestcv: 3 (0)", is this best? what does "0" in "bestcv: 3 (0)" mean?

Thank you very much!

Miao

Parts of results are attached below:

==> treePL2769972_0.1.out <==
you may want to set the plsimaniter > 100000
result: 4
 final: 3128607.6 diff: 355884.83
best: 1(1) bestad: 1 (1) bestcv: 3 (0)
PLACE THE LINES BELOW IN THE CONFIGURATION FILE
opt = 1
moredetail
optad = 1
moredetailad
optcvad = 3

==> treePL2769972_1.out <==
 final: 3207121.5 diff: 110930.04
setting NLOPT parallel : LD_MMA
you may want to set the plsimaniter > 100000
result: 4
 final: 3000710.2 diff: 317341.38
best: 1(0) bestad: 1 (0) bestcv: 3 (0)
PLACE THE LINES BELOW IN THE CONFIGURATION FILE
opt = 1
optad = 1
optcvad = 3

==> treePL2769972_10.out <==
you may want to set the plsimaniter > 100000
result: 4
 final: 3050738.9 diff: 2588895
best: 1(1) bestad: 1 (1) bestcv: 0 (0)
PLACE THE LINES BELOW IN THE CONFIGURATION FILE
opt = 1
moredetail
optad = 1
moredetailad
optcvad = 0

==> treePL2769972_100.out <==
setting NLOPT parallel : LD_MMA
you may want to set the plsimaniter > 100000
result: 4
 final: 3046957.5 diff: 280371.75
best: 1(0) bestad: 1 (1) bestcv: 0 (0)
PLACE THE LINES BELOW IN THE CONFIGURATION FILE
opt = 1
optad = 1
moredetailad
optcvad = 0

==> treePL2769972_1000.out <==
setting NLOPT parallel : LD_MMA
you may want to set the plsimaniter > 100000
result: 4
 final: 3149824.2 diff: 254039.98
best: 1(0) bestad: 1 (1) bestcv: 3 (0)
PLACE THE LINES BELOW IN THE CONFIGURATION FILE
opt = 1
optad = 1
moredetailad
optcvad = 3

==> treePL2769972_10000.out <==
 final: 3333963.1 diff: 95658.855
setting NLOPT parallel : LD_MMA
you may want to set the plsimaniter > 100000
result: 4
 final: 3164714.8 diff: 264907.15
best: 1(0) bestad: 1 (0) bestcv: 3 (0)
PLACE THE LINES BELOW IN THE CONFIGURATION FILE
opt = 1
optad = 1
optcvad = 3

**Comment by LuaBgd** [comment]
Hi, 
This would also help me! I don't find much documentation about it.
Thank you,
Bests,
Luana

**Comment by kjlmaurin** [comment]
Hello! I would like an answer to this too.
