### ISSUE TITLE
Configuration of adolc

### ISSUE THREAD

**Issue by TomCarr** [blackrim/treePL#23]
I am having trouble configuring the adolc dependency. 

sudo ./configure --with-openmp-flag=-fopenmp --prefix=/usr

configure: error: cannot find install-sh, install.sh, or shtool in autoconf "."/autoconf

I am unsure how to get around this...
Thanks.

**Comment by josephwb** [comment]
Are you on linux? Are you sure have all of the dependencies? Try:
```
sudo apt-get install autogen libtool shtool automake autoconf
```
and retry.
