### ISSUE TITLE
Estimating error around dates?

### ISSUE THREAD

**Issue by burbrink** [blackrim/treePL#24]
First off, great program! It has solved a lot of problems for me.

I was wondering if you had developed a way to generate error around dates? I seem to remember Sanderson suggesting that error in PL dates could be generated by using 1) the curvature of the likelihood surface (not optimal), or 2) estimating PL dates by throwing in a distribution of trees (bootstraps or Pp).

Any ideas on what do here would be much appreciated (I want to include downstream dating error for comparative phylo methods).

Thanks.

Frank

**Comment by josephwb** [comment]
FWIW I _believe_ the only route available at the moment is with the tree distribution. This typically involves bootstrap trees, because if you were doing Bayesian analyses you would be using BEAST in the first place! :bowtie:

**Comment by burbrink** [comment]
Thanks! I figured that was the option.

 I suppose I will loop it over the distributions of BS trees then. I guess I could get a Pp distribution on a fixed topology If had to (though for 732 taxa and over 400 loci is not optimal for something like that).

**Comment by josephwb** [comment]
The tricky bit is to make sure that your constraints (i.e. MRCA statements) are placed consistently on the various trees (I'm sure you know this). In the past I had R code to analyze individual trees and write out a treePL config file. This would, for example, get rid of redundant constraints. Not too difficult to do, but I can (try to!) find the code and put it in the repo.

**Comment by burbrink** [comment]
That is for sure an issue. 

However, the problem is that with a genomic dataset of this size, I am simply optimizing all of the genome data on the species trees to generate branch lengths in substitution probabilities. I can "easily" generate a distribution of substitution rates on this single species tree, but can't really do anything resembling relaxed phylogenetics. Perhaps this is tense phylogenetics?

**Comment by josephwb** [comment]
Indeed: [the past sure is tense](http://biorxiv.org/content/early/2017/03/04/113720) (to be clear: going for the joke here, not the shameless self-promotion!).

Good that you don't have to worry about phylo conflict; will things much easier. Good luck!

**Comment by burbrink** [comment]
Just a follow up. Say you have your bootstrapped trees (conforming to some species tree) in a folder that also includes your control file (control), the treePL executable, and this loop (treepl_loop.R) then just use this R script to run everything (provided that lambda is the same for each replicate):

x<-list.files()
x<-x[-grep("control",x)]
x<-x[-grep("treePL",x)]
x<-x[-grep("treepl_loop.R",x)]


for(i in 1:length(x)){
  y<-readLines("control.txt")
  y[1]<-paste("treefile =",x[i])
  y[15]<-paste("outfile = outPL_",x[i],sep="")
  write(y,"control.txt")
  system("treePL control.txt",ignore.stdout = T)
  print(i)
}


Co-authored with Marcelo Gehara

**Comment by josephwb** [comment]
@burbrink That could be useful for running the analyses in parallel (but would require altering your R code from a for loop; not too difficult), but treePL handles multiple trees natively. So you could just do:
```
cat *.tre > all.trees # if the trees are in different files
treePL control_file # where control_file obviously mentions 'all.trees'
```

**Comment by burbrink** [comment]
Good point, I could have just done that with an apply fxn and put in parallel. But this is running lightning fast already (with 8 threads).

I had no idea treePL handled these natively. Reinventing the wheel.

Well kids, that is a good loop for controlling stuff from R anyhow...
