### ISSUE TITLE
MRCA

### ISSUE THREAD

**Issue by UzmaSalam** [blackrim/treePL#26]
Hello, I'm new to treePL, is there any detailed description or manual or google group for this software. I wouldn't understand MRCA (most recent common ancestor) in run option because there are two names of species. is this the root of tree? secondly in which format I need to save this configure file?
Thank you

**Comment by josephwb** [comment]
There is a [wiki](https://github.com/blackrim/treePL/wiki) which describes things.

Each node in a tree represents the (hypothetical) ancestor of the descendant tips. An MRCA is the _most recent_ ancestor of a set of tips. For example, in the following tree:

```(((A,B)1,C)2,((D,E)3,F)4)5;```

the root (denoted with `5`) is _an_ ancestor of A and B, but node `1` is _the most recent_ ancestor. MRCA statements are used to identify specific nodes to place constraints on the ages of nodes (maximum or minimum ages). Only two descendant tips need to be specified. For example, node `2` is the ancestor of tips A, B, and C, but it can be specified with either the tip pairs `A and C` or `B and C` (but not `A and B`, as that identifies node `1`).

The config file needs to be plain text.
HTH.

**Comment by UzmaSalam** [comment]
Thank you so much Joseph, I got the point now. I'm going to constraints ingroup ages so that mean I need to mention ingroup and then two taxa according to you explained. so if I want to fixed that like 42 million years so I just need to write 42 or need to convert this value into million?

**Comment by josephwb** [comment]
You can use 42 (don't use 42,000,000).

To fix the age of a node, you put both an upper and lower constraint:

mrca = INGROUP tip1 tip2
min = INGROUP 42
max = INGROUP 42

**Comment by UzmaSalam** [comment]
Thank you Joseph. Best,

**Comment by UzmaSalam** [comment]
I don't know I got this error, when I run:

tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
tiny branch length at internal node. setting to 0.00048076923
problem with taxa for mrca INGROUP = [MRCA doesn't exist

Please see and help me out.
Thank you,
Best,

**Comment by josephwb** [comment]
Can you post your tree and config file?

**Comment by UzmaSalam** [comment]
I have sent you via email. Thank you,
Best,

**Comment by josephwb** [comment]
I don't know if that was directed at me, but I never received an email.

**Comment by UzmaSalam** [comment]
I have sent to this address: notifications@github.com
is that you?

**Comment by josephwb** [comment]
Nope! Try phylo.jwb @ gmail.com

**Comment by UzmaSalam** [comment]
fine but whose that address?

**Comment by UzmaSalam** [comment]
sent.
