### ISSUE TITLE
Node ages

### ISSUE THREAD

**Issue by UzmaSalam** [blackrim/treePL#28]
Hi, I'm confused in node ages, what parameters we need to optimize in order to get correct node ages. Every time I got tree with greater node ages when I used different values for smooth (0.001-10000). How could I possibly get lower node ages?
Thank you,
Best,
Uzma

**Comment by josephwb** [comment]
@UzmaSalam You need to run a cv analysis to determine the optimal value of smoothing. Then, turn off cv, set that value of smoothing, and you're done.

**Comment by UzmaSalam** [comment]
Thank you Joseph. Best,

**Comment by UzmaSalam** [comment]
I tried this:
treefile = intree
numsites = 2080
mrca = INGROUP taxa1 taxa2
min = INGROUP 42.2
max = INGROUP 42.2
outfile = outtree
thorough
prime
cv
cvoutfile = outfile
nthreads = 16
Then I got this at the end of run:
opt = 1
moredetail
optad = 1
moredetailad
optcvad = 4
moredetailcvad
So, I added this in my configure file then run but I didn't get smoothing here and the out tree has node ages greater than actually reported. 
Did I run correctly, 
Best,

**Comment by josephwb** [comment]
Your config file _after_ priming should look like this:
```
treefile = intree
numsites = 2080
mrca = INGROUP taxa1 taxa2
min = INGROUP 42.2
max = INGROUP 42.2
outfile = outtree
thorough
#prime
cv
cvoutfile = cv.outfile.txt
nthreads = 16
opt = 1
moredetail
optad = 1
moredetailad
optcvad = 4
moredetailcvad
```
Note that "prime" is commented out (if it is not, it will just prime again). The above config will perform a cv analysis. I cannot recall the defult, but you can set the max/min of the smoothing values used in cv with:
```
cvstart = 0.0001
cvstop = 10000
```
When cv completes the results are in the file "cv.outfile.txt". Find the smallest cv score. Say that is 1000. Set it in the config file (while turning off cv):
```
treefile = intree
numsites = 2080
mrca = INGROUP taxa1 taxa2
min = INGROUP 42.2
max = INGROUP 42.2
outfile = outtree
thorough
#prime
#cv
#cvoutfile = cv.outfile.txt
smoothing = 1000
nthreads = 16
opt = 1
moredetail
optad = 1
moredetailad
optcvad = 4
moredetailcvad
```
And the tree that results is your chronogram. Note that each stage of the cv analysis will produce a chronogram; you do not want those (as they do not use the optimal smoothing value). You want the chronogram from the final run above.

HTH.

**Comment by UzmaSalam** [comment]
okay, I'm running the configure file.
Thank you,
Best,

**Comment by UzmaSalam** [comment]
Hi, I got these results, which should I use for smoothing? I'm sorry I didn't get this.
chisq: (10000) 33888
chisq: (1000) 33856.5
chisq: (100) 33654.7
chisq: (10) 32396.2
chisq: (1) 20864.8
chisq: (0.1) 15961.4
chisq: (0.01) 9309.16
chisq: (0.001) 8436.88
chisq: (0.0001) 8300.59

thank you,
Best,

**Comment by josephwb** [comment]
The best smoothing value has the lowest error. Sp this would be 0.0001. That is quite small. Are you sure the tree is rooted correctly? Maybe you should send me your phylogram and config file?

**Comment by UzmaSalam** [comment]
yes I have sent you previously but I'm sending you on your email. Thank you,
Best,

**Comment by UzmaSalam** [comment]
sent an email to you!

**Comment by UzmaSalam** [comment]
The tree that I have gotten using 0.0001 still has high node ages than expecting and reported. I don't know how to get true node ages.

**Comment by josephwb** [comment]
Everything looks good to me. What is the issue? If you have more fossils you can specify more constraints.

**Comment by UzmaSalam** [comment]
okay then thank you.
Best,
