### ISSUE TITLE
Quick question : is there a linux version of TreePL ?

### ISSUE THREAD

**Issue by LuaBgd** [blackrim/treePL#29]
Thanks a lot !

Lua
phD student

**Comment by josephwb** [comment]
There is not yet an apt-get way to install, but [compilation on linux](https://github.com/blackrim/treePL/wiki/Installation) is very easy.

**Comment by LuaBgd** [comment]
Thank you very much  for your answer I hadn't noticed the codes were in src !

**Comment by josephwb** [comment]
(^_<)
