### ISSUE TITLE
How to reduce the number of constraints

### ISSUE THREAD

**Issue by LuaBgd** [blackrim/treePL#31]
Hi everyone,

I am also using treePL with constraints and I got the error message: "Failed setting feasible start rates/dates after 10 attempts. Aborting."
I obtained ages for the nodes to constrain from a tree, previsouly dated using treePL so they shouldn't be conflicting constraints as you present them : one node close to the tips older than one closer to the root. Is there other cases where constraints can be conflicting that I could check for ?
I am dating a tree with 2340 species and using around 200 constraints, is it too much ? how can I choose the best ones ?

Thank you very much for your answers !

Have a nice day !

Luana
phD student
Toulouse, FRANCE

**Comment by josephwb** [comment]
@LuaBgd Are you certain there are no conflicting constraints? Even just 1 will make make an analysis impossible. For example, if there are any topological differences between your tree and the tree you referenced, then some constraints can be redundant or conflicting. I have (R) code that can check constraint consistency. If you post your tree & config file I can test things for you. If it proves useful I can clean it up a bit and put it in the treePL repo.

**Comment by LuaBgd** [comment]
Hi !

Thank you very much for your answer! 
I am definitely not certain there are no conflicting constraints but I extracted them as follow:
 - I extracted all node ages of a dated tree
- kept ages for nodes leading to a monophyletic group
- check in the phylogeny I want to date, if this node exists (is the same taxonomic group also monophyletic there?)
- removed contraints pointing the same node

So, I thought everything should be already consistent... But yes I can post the tree and the constraints, that would be lovely of you to look at it!

Thank you very much,
Luana

**Comment by LuaBgd** [comment]
My configuration file :

treefile= mt.tree
smooth = 100
numsites = 3475
mrca= Cladistia Erpecala00 Polyretr00
min= Cladistia 424.8
max= Cladistia 424.8
mrca= Actinopteri Bedogeay00 Psepglad00
min= Actinopteri 409.4
max= Actinopteri 409.4
mrca= Chondrostei Scapplat00 Psepglad00
min= Chondrostei 241.804369
max= Chondrostei 241.804369
mrca= Neopterygii Bedogeay00 Atraspat00
min= Neopterygii 241.804369
max= Neopterygii 241.804369
mrca= Holostei Amiacalv00 Atraspat00
min= Holostei 382.6
max= Holostei 382.6
mrca= Teleostei Bedogeay00 Sacclave00
min= Teleostei 29.2
max= Teleostei 29.2
mrca= Elopomorpha Elophawa00 Sacclave00
min= Elopomorpha 29.2
max= Elopomorpha 29.2
mrca= Osteoglossocephalai Bedogeay00 Hiodterg00
min= Osteoglossocephalai 350.1
max= Osteoglossocephalai 350.1
mrca= Osteoglossomorpha Xenonigr00 Hiodterg00
min= Osteoglossomorpha 138.9
max= Osteoglossomorpha 138.9
mrca= Clupeocephala Bedogeay00 Chanchan00
min= Clupeocephala 38.592824
max= Clupeocephala 38.592824
mrca= Otomorpha Bathmacr00 Chanchan00
min= Otomorpha 322.5
max= Otomorpha 322.5
mrca= Clupei Stolcomm00 Dentclup00
min= Clupei 267.9
max= Clupei 267.9
mrca= Alepocephali Bathmacr00 Platapus00
min= Alepocephali 21.61551
max= Alepocephali 21.61551
mrca= Ostariophysi Vailmaas00 Chanchan00
min= Ostariophysi 283.3
max= Ostariophysi 283.3
mrca= Anotophysa Gonoabbr00 Chanchan00
min= Anotophysa 196.2
max= Anotophysa 196.2
mrca= Otophysa Vailmaas00 Hypoinco00
min= Otophysa 196.2
max= Otophysa 196.2
mrca= Cypriniphysae Vailmaas00 Tanatana00
min= Cypriniphysae 40.5485839999999
max= Cypriniphysae 40.5485839999999
mrca= Characiphysae Cithcong00 Boulmacu00
min= Characiphysae 40.373487
max= Characiphysae 40.373487
mrca= Euteleosteomorpha Bedogeay00 Ijimdofl00
min= Euteleosteomorpha 35.64527
max= Euteleosteomorpha 35.64527
mrca= Eurypterygia Bedogeay00 Synomyop00
min= Eurypterygia 273.8
max= Eurypterygia 273.8
mrca= Cyclosquamata Lestatla00 Synomyop00
min= Cyclosquamata 227.1
max= Cyclosquamata 227.1
mrca= Ctenosquamata  Bedogeay00 Scoptris00
min= Ctenosquamata  9.53282899999999
max= Ctenosquamata  9.53282899999999
mrca= Myctophata Diapluet00 Scoptris00
min= Myctophata 104.854707
max= Myctophata 104.854707
mrca= Acanthomorphata Bedogeay00 Polylowe00
min= Acanthomorphata 81.631435
max= Acanthomorphata 81.631435
mrca= Lampripterygii Zucris00 Tractrac11
min= Lampripterygii 250.6
max= Lampripterygii 250.6
mrca= Percopsaria Aphrsaya00 Perctran00
min= Percopsaria 230.2
max= Percopsaria 230.2
mrca= Zeiogadaria Zenijapo00 Merlmerl00
min= Zeiogadaria 188.9
max= Zeiogadaria 188.9
mrca= Zeiariae Zenijapo00 Parapaci00
min= Zeiariae 47.084649
max= Zeiariae 47.084649
mrca= Gadariae Stylchor00 Merlmerl00
min= Gadariae 27.465346
max= Gadariae 27.465346
mrca= Acanthopterygii Bedogeay00 Anomkato00
min= Acanthopterygii 53.278988
max= Acanthopterygii 53.278988
mrca= Percomorphaceae Bedogeay00 Lampnige00
min= Percomorphaceae 16.923695
max= Percomorphaceae 16.923695
mrca= Cichlomorphae Paremacu00 Parapoll00
min= Cichlomorphae 198.6
max= Cichlomorphae 198.6
mrca= Atherinomorphae Bedogeay00 Austchar00
min= Atherinomorphae 175.9
max= Atherinomorphae 175.9
mrca= Mugilomorphae Chaeprob00 Mugicure00
min= Mugilomorphae 18.169743
max= Mugilomorphae 18.169743
mrca= Blenniimorphae Salafasc00 Enneethe00
min= Blenniimorphae 99.074809
max= Blenniimorphae 99.074809
mrca= Gobiaria Odonplat00 Kurtgull00
min= Gobiaria 172.9
max= Gobiaria 172.9
mrca= Syngnatharia Macrscol00 Upentrag00
min= Syngnatharia 99.30000001
max= Syngnatharia 99.30000001
mrca= Pelagiaria Scomboop00 Iciclock00
min= Pelagiaria 32.767956651
max= Pelagiaria 32.767956651
mrca= Batrachoidiaria Batrtris00 Porimyri00
min= Batrachoidiaria 23.079322677
max= Batrachoidiaria 23.079322677
mrca= Ophidiaria Diplbrac00 Lampnige00
min= Ophidiaria 39.563059309
max= Ophidiaria 39.563059309
outfile = mt.dated.tre

**Comment by Belinda333** [comment]
Hi everyone,

would it possible to share that R code to check constraint consistency? I have a similar issue and a lot of large trees to date where manually checking would take forever.... Thanks a lot!

Best wishes,
Belinda
