### ISSUE TITLE
Failed adolc compilation, ubuntu 16.04

### ISSUE THREAD

**Issue by TristanLefebure** [blackrim/treePL#35]
Hello

I tried to compiled the provided adol-c sources, but got the following problem on a ubuntu 16.04 server:

```
cd deps/adol-c
autoreconf -fi
configure.ac:43: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:44: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1
```
Anyone with a solution ?
Best
--
Tristan

**Comment by blackrim** [comment]
Hm, not sure what the problem is there. I have an updated fix for standard ADOLC that i will push shortly and you can try that.

**Comment by blackrim** [comment]
the updated ADOLC should work now
