### ISSUE TITLE
treePL not working properly

### ISSUE THREAD

**Issue by gavrucent** [blackrim/treePL#37]
I am trying to install treePL on Mac 10.13.6. I installed Homebrew and then installed treePL with 

brew install brewsci/bio/treepl

When i try to run the provided tests to see if it works properly:
 brew test -v treepl
I get the following error:
==> /usr/local/Cellar/treepl/2017.05.23/bin/treePL clock.cppr8s
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Referenced from: /usr/local/Cellar/treepl/2017.05.23/bin/treePL
  Reason: image not found
Error: brewsci/bio/treepl: failed
undefined method `map' for nil:NilClass
Did you mean?  tap

I would appreciate any help with this issue.

**Comment by justincbagley** [comment]
Hi, I installed treePL with Homebrew and had it working a few months ago (early 2019). However, now, in June 2019, I am having a new issue on macOS 10.13+ with the Homebrew treePL install. Just this week, treePL started throwing a dyld issue. So, I uninstalled treePL and reinstalled with Homebrew, but I encountered the same dyld issue. Log below.

```
Justin:~ justinbagley$ brew install brewsci/bio/treepl
Updating Homebrew...
==> Installing treepl from brewsci/bio
==> Downloading https://linuxbrew.bintray.com/bottles-bio/treepl-2017.05.23_2.sierra.bottle.tar.gz
Already downloaded: /Users/justinbagley/Library/Caches/Homebrew/downloads/2f8b64986bd7aec0acc56b7ca54462347d0ad3de05454787e10aaa120e57f955--treepl-2017.05.23_2.sierra.bottle.tar.gz
==> Pouring treepl-2017.05.23_2.sierra.bottle.tar.gz
Warning: brewsci/bio/treepl dependency gmp was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/treepl/2017.05.23_2: 65 files, 2.2MB
Justin:~ justinbagley$ 
Justin:~ justinbagley$ 
Justin:~ justinbagley$ 
Justin:~ justinbagley$  treePL treePL_centropogonid_and_Burm_ub_lb_2calib_rootedTree_prime.configuration
dyld: Library not loaded: @@HOMEBREW_CELLAR@@/treepl/2017.05.23_2/libexec/lib64/libadolc.1.dylib
  Referenced from: /usr/local/bin/treePL
  Reason: image not found
Abort trap: 6
Justin:542genes_concat_56t_raxml_genepart_unrooted_100boot_bipartitions_on_best justinbagley$ 
```

Checking the homebrew cellar, here's what's inside the lib64/ dir, and you can see libadolc.1.dylib is not present:

```
justinbagley$ cd /usr/local/Cellar/treepl/2017.05.23_2/libexec/lib64/
Justin:lib64 justinbagley$ lsl
       4
Justin:lib64 justinbagley$ ls
libadolc.1.dylib libadolc.a       libadolc.dylib   libadolc.la
```

Please let me know if I can fix this on my side, or if this is a bug that you need to fix on your end. Would like to get a solution on this soon. Thanks.

Best,
Justin

**Comment by josephwb** [comment]
FWIW I just tried a fresh install on Mac 10.14.5 and get the exact same error:
```
dyld: Library not loaded: @@HOMEBREW_CELLAR@@/treepl/2017.05.23_2/libexec/lib64/libadolc.1.dylib
  Referenced from: /usr/local/bin/treepl
  Reason: image not found
Abort trap: 6
```

**Comment by BiodivGenomic** [comment]
Hi,
I'm in the same situation with a fresh install of treePL on macosX 10.13.6....
