### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by tseemann** [blackrim/treePL#38]
It has been a few years and no commits since 1.0 release.

**Comment by blackrim** [comment]
It is being maintained but new functionality is not on the table just yet.

**Comment by tseemann** [comment]
There are many bugs that have been reported but ignored though?

**Comment by blackrim** [comment]
Hm, to which are you referring? I see feature requests and some general questions about usage but I don't see bugs. Obviously, this is academic software without a full-time coder. However, if there is a bug that is not addressed, I am happy to fix that.

**Comment by tseemann** [comment]
segfault with certain characters?
https://github.com/blackrim/treePL/issues/39

**Comment by blackrim** [comment]
yeah, the person issuing that is a co-developer of this that was just intending to port some code we have to solve this issue from another project (phyx) but hasn't yet. Nevertheless, if this is an issue for you , I can port it over real quick. 

TBH, we are trying to extend the method behind this software and so there is a more extensive overhaul coming. But again, if this one is an issue for you, I can push a fix soonish.

**Comment by tseemann** [comment]
No i was just being contrary and you should ignore me.

I think my original question 2 years ago was to see whether i should bother packaging it into brew and conda. I didn't get a response so I didn't do it.

**Comment by blackrim** [comment]
Haha, no problem. Academic backlog slows down some of these if I they
function for most use-cases. Nevertheless, I could be more attentive!
