### ISSUE TITLE
configure does not honour options specified

### ISSUE THREAD

**Issue by josephwb** [blackrim/treePL#43]
I tried passing the following to configure:
```
./configure CXX=/usr/local/bin/g++-9 CC=/usr/local/bin/gcc-9
```
but the Makefile looks like this:
```
CC := $(CC)
CP := $(CXX) -std=c++11
```
Unfortunately on mac, this points to clang, so no openmp.

We have this option in phyx, so probably just a matter of copying over the relevant bits.

**Comment by blackrim** [comment]
Hey Joseph 
Any chance you have the relevant bits on hand? Can add it and close this or if you want a pull request feel free

**Comment by josephwb** [comment]
I can check in a bit.

**Comment by josephwb** [comment]
Ok got it. Will push in a second.

**Comment by blackrim** [comment]
Awesome! Thanks

**Comment by josephwb** [comment]
Fixed with https://github.com/blackrim/treePL/pull/45
