### ISSUE TITLE
How to run the "wiggle" option mentioned in the paper?

### ISSUE THREAD

**Issue by anhong11** [blackrim/treePL#44]
While reading the paper I noticed the option for creating confidence intervals, "We have also provided a ‘wiggle’ option that will report divergence times that are within two log likelihood units of the best likelihood, suggested by Edwards (1992) as a confidence window." However, when looking at the options for parameters, I cannot find this wiggle feature. My question is was this parameter removed?

**Comment by blackrim** [comment]
The option is "mapspace" in the configuration file. Hope that helps!
