### ISSUE TITLE
How to run treePL?

### ISSUE THREAD

**Issue by kjlmaurin** [blackrim/treePL#46]
Hello,

Here is a very basic question, but surprisingly I cannot find any answer to it online: how do I run treePL once installed?

The test run works, but when I am trying to replace "test" in the command line `brew test -v treepl` by my script (a .txt file), with the path to it, I get a `Unknown command:` [my file] error message.
I have tried many combinations of this command line, like swapping `treepl` and my file, not putting `brew`, adding `./` before `treepl`, adding the path to the treePL script, etc. but nothing works.

Can someone please tell me how they run it?
Many thanks

**Comment by kjlmaurin** [comment]
Whoops sorry ignore this. I got confused about the instructions in the "Run Options" page, but not I managed to run it. I have issues with the run, will come back here if I cannot solve them :)

**Comment by BiodeB** [comment]
Dear Sir,

Have you solve this issue, I'm having same problem. I have installed treePL through brew install. Now how can I ran my file through this kindly guide me.

Thanks

**Comment by kjlmaurin** [comment]
Hello,
You must open the command window of whichever plaftorm you are using, then type
'treePL /path/to/your/configuration/file.txt'
Maybe use 'treepl' instead of 'treePL', I cannot remember what I used (I have not made a run in months, so this detail just slipped my mind ah ah!). And for the config file, use .txt or whichever format your config file has. This should work if treePL has been installed properly.
Cheers
