### ISSUE TITLE
Tree is invalid: missing concluding semicolon

### ISSUE THREAD

**Issue by kjlmaurin** [blackrim/treePL#47]
Hello,

I am trying to run a treePL analysis with a .tre file but I get this error message:
`Tree is invalid: missing concluding semicolon. Exiting`

I have checked my .tre file, and all the semicolons are here at the end of each line. Here is the structure of the file (I can email it for debugging if needed):
`#NEXUS`
`begin taxa;`
`	dimensions ntax=19;`
`	taxlabels`
`{names of my taxa}`
`;`
`end;`
`begin trees;`
`	tree TREE1 = [&R] {tree};`
`end;`
`begin figtree;`
`{list of "set" commands, each with their semicolon}`
`end;`

I have tried removing or adding bits of code like round brackets, square brackets, the `#NEXUS` tag, figtree block, etc... nothing solves the problem. Also, no online help found for this case. I am running treePL on Ubuntu.

Many thanks in advance for your help.
Kind regards,
Kévin

**Comment by josephwb** [comment]
Try deleting the block `begin taxa;` through the first `end;`. The first line after `#NEXUS` should be `begin trees;`. Also delete the entire figtree block.

If that does not work, post the tree here; I have code to extract a non-annotated tree.

**Comment by kjlmaurin** [comment]
Hello,

Thank you for you reply. I still get the same error message.

Here is the tree:
`tree tree_1 = [&R] (((((((((JAN4:1.0,(JAN8:1.0,JAN5:1.0)[&boot=0.999]:1.0)[&boot=0.9762]:1.0,JAN2:1.0)[&boot=0.9474]:1.0,(JAN7:1.0,JAN6:1.0)[&boot=0.9911]:1.0)[&boot=1.0]:1.0,JAN1:1.0)[&boot=0.9365]:1.0,JAN3:1.0)[&boot=1.0]:1.0,(BOT1:1.0,(BOT2:1.0,(BOT2:1.0,BOT3:1.0)[&boot=1.0]:1.0)[&boot=0.876]:1.0)[&boot=0.998]:1.0)[&boot=1.0]:1.0,SCH:1.0)[&boot=1.0]:1.0,((HUD:1.0,TRI:1.0)[&boot=1.0]:1.0,(SCT:1.0,(AST2:1.0,((AST1:1.0,AST3:1.0)[&boot=1.0]:1.0,AST4:1.0)[&boot=1.0]:1.0)[&boot=1.0]:1.0)[&boot=1.0]:1.0)[&boot=1.0]:1.0)[&boot=1.0]:1.0,(((OGC3:1.0,OGC1:1.0)[&boot=1.0]:1.0,(OGC2:1.0,OGC4:1.0)[&boot=1.0]:1.0)[&boot=1.0]:1.0,((CUT:1.0,PHY:1.0)[&boot=1.0]:1.0,(LEA:1.0,BOT3:1.0)[&boot=1.0]:1.0)[&boot=1.0]:1.0)[&boot=1.0]:1.0,(LOB:1.0,WIL:1.0)[&boot=1.0]:1.0);`

I would be happy if you could share this script and explain how to use it, I would appreciate being autonomous with this :)

Kind regards,
Kévin

**Comment by josephwb** [comment]
A couple of things:

First, the annotations `[&boot=1.0]` should be removed, as I don't think treePL supports this (I could be wrong. The phyx program `pxcltr` can do this.

Second, the tree contains duplicate taxon names (e.g., "BOT2"), which is not allowed. I cannot even get a tree reader to open the tree.

Finally, the tree does not appear to be a phylogram, as all edge lengths are 1.0. treePL requires a phylogram as input (i..e, a tree where the branches are in units of expected number of substitutions per site).

HTH.
Joseph.

**Comment by kjlmaurin** [comment]
Oh wow, sorry about all of this.

For error 1, I will investigate this package.

For error 2, my bad, I replaced my super long sequences names for something shorter in the .tre file to make it easier to read, but I made a mistake obviously.

For error 3, I did not know about this. I will have a look at how to get a phylogram from RAxML (I'm self-teaching so it could take a while...), then I will get back to you if it still does not work, even after implementing `pxcltr`.

Many thanks,
Kévin

**Comment by kjlmaurin** [comment]
Hello,

I managed to build a phylogram with RAxML (well, I believe it is one, given that I have numbers that very much look like rates of substitutions per sites), but I still get the same error message. In my file I only kept the `trees` block, as advised. I even made a trial with and without bootstraps values, just in case, but still, same problem.

Here are my trees, in case it helps:
Only rates
`begin trees;`
	`tree tree_1 = [&R] ((((((((((JAN4:4.4E-5,JAN8:1.0E-6):2.85E-4,JAN5:1.53E-4):0.001066,JAN2:0.001805):3.24E-4,JAN7:0.001542):8.57E-4,JAN6:0.003482):0.008102,JAN1:0.038895):0.001467,JAN3:0.021262):0.00334,(BOT1:0.004055,(BOT2:0.001691,BOT3:5.03E-4):0.002653):0.006499):0.006632,(OGC1:0.001099,(OGC3:4.84E-4,(OGC2:1.97E-4,OGC4:1.1E-4):7.25E-4):7.34E-4):0.011761):0.002624,((AST4:0.01398,AST3:0.050939):0.001405,(AST2:0.028342,AST1:0.033601):0.001781):0.002624);`
`end;`

With bootstraps
`begin trees;`
	`tree tree_1 = [&R] ((((((((((JAN4:4.4E-5,JAN8:1.0E-6)[&boot=100]:2.85E-4,JAN5:1.53E-4)[&boot=100]:0.001066,JAN2:0.001805)[&boot=100]:3.24E-4,JAN7:0.001542)[&boot=100]:8.57E-4,JAN6:0.003482)[&boot=100]:0.008102,JAN1:0.038895)[&boot=100]:0.001467,JAN3:0.021262)[&boot=100]:0.00334,(BOT1:0.004055,(BOT2:0.001691,BOT3:5.03E-4)[&boot=100]:0.002653)[&boot=100]:0.006499)[&boot=100]:0.006632,(OGC1:0.001099,(OGC3:4.84E-4,(OGC2:1.97E-4,OGC4:1.1E-4)[&boot=100]:7.25E-4)[&boot=100]:7.34E-4)[&boot=100]:0.011761)[&boot=100]:0.002624,((AST4:0.01398,AST3:0.050939)[&boot=98]:0.001405,(AST2:0.028342,AST1:0.033601)[&boot=98]:0.001781)[&boot=100]:0.002624);`
`end;`

Any idea what's going on?

**Comment by josephwb** [comment]
Reduce the tree to a newick:
```
((((((((((JAN4:4.4E-5,JAN8:1.0E-6):2.85E-4,JAN5:1.53E-4):0.001066,JAN2:0.001805):3.24E-4,JAN7:0.001542):8.57E-4,JAN6:0.003482):0.008102,JAN1:0.038895):0.001467,JAN3:0.021262):0.00334,(BOT1:0.004055,(BOT2:0.001691,BOT3:5.03E-4):0.002653):0.006499):0.006632,(OGC1:0.001099,(OGC3:4.84E-4,(OGC2:1.97E-4,OGC4:1.1E-4):7.25E-4):7.34E-4):0.011761):0.002624,((AST4:0.01398,AST3:0.050939):0.001405,(AST2:0.028342,AST1:0.033601):0.001781):0.002624);
```
and it runs fine. I had thought it accepts Nexus trees as input but I guess that is not the case. So make sure you have no annotations at all in your tree(s).

**Comment by kjlmaurin** [comment]
Hi Joseph,
Awesome, it does work indeed :) Yes the documentation says it takes `.tre` files, so I thought a FigTree nexus would do. I get weird results for now, so I guess it is a matter of optimising the run. Many thanks!
Kind regards,
Kévin
