### ISSUE TITLE
Writing a for loop for treepl?

### ISSUE THREAD

**Issue by dylanHco** [blackrim/treePL#52]
Hello,

I am trying to write a simple for loop in bash for treepl. I am novice at programming and have been stuck on this for awhile. I was wondering if yall had any suggestions? This is what I have so far: 

for filename in ./TESTLOOP/*.tre;
do treePl cd.. config8 ;
done;

for the input tree = "$filename" # basically a directory with all the tree files
output tree = "$filename".dated.tre # I am confused about how to set up the output directory

When I run this i get this error multiple times: 

treePL version 1.0
you need more arguments.

Any suggestions are greatly appreciated, thanks!

**Comment by josephwb** [comment]
If you are using the same config file for all the trees (say, trees from a common bootstrap or posterior distribution), this will work:
```
#!/bin/bash

# assumes:
# 1. a single treePL config file 'treepl.config' for all trees
#    - this assumes that all settings are the same
#       - constraints, mrcas, smoothing parameter, etc.
# 2. the tree filename specified in the config file is 'test.tre'
#    - do not set an output file name. we will use the default of 'out_dates'
# 3. there is an existing directory called 'complete'

for f in *.tre; do
  # copy current tree into 'test.tre'
  cp $f test.tre
  
  # run treePL
  treePL treepl.config
  
  # rename and move results
  mv out_dates.tre complete/"${f%.*}".dates.tre
  mv out_dates.tre.r8s complete/"${f%.*}".r8s.tre
  
done;

# get rid of test.tre to clean up
rm test.tre
```
put the above code in a text file called `run_multi.sh` and do:
```
chmod 755 run_multi.sh
``` 
to make it executable. 
Make sure the output directory `complete` exists in the directory with the trees and single config file, and do:
```
./run_multi.sh
```
If you have separate config files for each tree, make sure they _do_ have output file names specified (if not, one result will just overwrite the previous). Everything (tree and config files) can reside in the same directory, and then your bash script would simply be:
```
#!/bin/bash

for f in *.config; do
  treePL $f
done;
```

HTH.

**Comment by dylanHco** [comment]
Hi Joseph,

Thank you so much for this! I tried both, but in the end the second method worked for me.
