### ISSUE TITLE
Treepl+RaxML replicate trees

### ISSUE THREAD

**Issue by carolinaamg** [blackrim/treePL#56]
Hello!

I have been using treePL to date a phylogenetic tree but I generated replicate trees with RaxML (same topology but branch lengths varied) and ran treePL on each of these trees in order to get confidence intervals for each node. I already calculate CI values but I am still struggling to find a program in which I can add those CI values separately (such that each node has a bar). 

Any suggestions for a good tree viewer? 

Thank you!

Carolina.

**Comment by josephwb** [comment]
@carolinaamg I realize this is 2 years late but if you format your trees such that BEAST's treeannotator can read them (i.e., a nexus tree log file) then it can summarize the breadth of node ages for you, and you can plot them in FigTree.
