### ISSUE TITLE
The root time is biased towards the maximum time of the fossil which calibrated to the root.

### ISSUE THREAD

**Issue by XuWeiEvo** [blackrim/treePL#65]
Hi Stephen,

We used several fossils to calibrate the tree, as shown below. However, the divergence times were generally much older than expected. In particular, the root time was exactly 290 million years ago, the same as the maximum time of node 1. It appears that treePL is not utilizing the minimum prior at all and is instead setting the ancestral divergence at the maximum of 290 million years ago. Could you please provide some insight into where the problem might have originated? Thank you.

treefile = input.tre
smooth = 0.1
numsites = 329958

mrca = node1 I3542 I19280
min = node1 247.2
max = node1 290

mrca = node2 I4423 I6469
min = node2 150

mrca = node3 I4423 I6444
min = node3 121.4

mrca = node4 I6453 I6444
min = node4 83.6

mrca = node5 I4373 I8555
min = node5 121.4

mrca = node6 I23592 I19280
min = node6 46.3

mrca = node7 I6469 I4424
min = node7 33.3

mrca = node8 I7783 I4424
min = node8 113

Best,
Wei Xu

**Comment by XuWeiEvo** [comment]
I have attempted to use various maximum time of the root values, but the resulting phylogeny only displays the same maximum time value. It seems that treePL is automatically setting the ancestral divergence at the maximum of the root prior. Could you please provide me with some guidance on how to address this issue?

**Comment by josephwb** [comment]
The cnstraints are not priors, but rather limits.

The root node is the hardest node of all to date. Think of a node toward the tips: it has a limit of 0 (the present), plus some constraint on an ancestral node; this effectively boxes it into a range of suitable ages. The root node is different: it only has the maximum constraint you impose. Plus, it has the smallest amount of information to date it: just the two descendant edges leading out from it. Getting out your maximum age constraint as a result is not atypical.

What you can do is try a range of root constraints, and see if they influence the ages of the younger nodes. If not, they are robust. If they are, perhaps add more outgroups to add more ancient constraints.

HTH.

**Comment by XuWeiEvo** [comment]
Thank you very much for such detailed explanations!
