### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by kldxgg** [blackrim/treePL#67]
I've tried a lot of different versions of R, but every time it's a tip 
"Warning in install.packages :
  package ‘treePL’ is not available for this version of R"
So what version of R can work with this package?

**Comment by josephwb** [comment]
treePL is a C++ program. AFAIK it has never been ported to R. The package [datelife](https://cran.r-project.org/web/packages/datelife/index.html) has wrappers for treePL, but they require treePL to be built and installed outside of R (i.e., somewhere the R path can find it).

HTH.
